### ISSUE TITLE
error occurred when trying to save model

### ISSUE THREAD

**Issue by Lchrodinger** [AliaksandrSiarohin/cuda-gridsample-grad2#1]
Hi, Siarohin. I'm using cuda_gridsample in my code to calculate the second backward of gridsample, but whenever i'm trying to save my torch model, an unexpected error always occur, i have tried torch.save() and dill.dump(), but neither of them ran successfully, do you have any idea what happened, any suggestions will be helpful.
Below are the error i encounted while running my code. I'm using python 3.9.13 and torch 1.10.0+cu113.
![1](https://user-images.githubusercontent.com/50990694/228712479-53d484c2-8aa6-4016-845e-4bbd0e137aec.png)
![2](https://user-images.githubusercontent.com/50990694/228712497-3ac0d921-6f46-4201-940d-8f18e7e1a51d.png)

**Comment by AliaksandrSiarohin** [comment]
Not sure that this is related. Can you try to save just a module with a single grid_sample, without anything else, to validate?

**Comment by Lchrodinger** [comment]
Thanks for reply, yeah, you're right. I've found the error, and it's not related to gridsample, thanks for your help, i'll close this issue.
